Repository team-Melissa/melissa-FE, pull requests merged in 2025-03, with the labels that each got.

#37 실 배포 환경 런타임 에러 디버깅을 위해 Sentry 도입
  app.config.ts
  metro.config.js
  package.json
  pnpm-lock.yaml
  src/app/_layout.tsx
Labels: :sparkles: feature

#39 Sentry가 개발 환경에서도 에러를 리포팅하는 문제 해결
  src/app/_layout.tsx
Labels: :bug: bug

#40 UI fixes by ms
  pnpm-lock.yaml
  src/components/AssistantList/AssistantCard/index.tsx
  src/components/AssistantList/styles.ts
  src/components/ProgressBar/styles.ts
  src/pages/MakeAssistant/Question/index.tsx
  src/pages/MakeAssistant/Question/styles.ts
Labels: 💅 design-tweak

#41 바텀 시트를 열어두고, 뒤로가기 버튼 클릭 시 앱이 종료되는 문제 해결
  src/pages/Calendar/DiaryBottomSheet/index.tsx
  src/pages/Calendar/DiaryBottomSheet/useBottomSheetBackHandler.ts
  src/pages/Calendar/index.tsx
Labels: :bug: bug

#44 Chore: 깃허브 issue 템플릿 추가
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: :memo: documentation

#45 깃허브 PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :memo: documentation

#49 채팅 페이지에 안내 텍스트 추가 및 채팅 인풋 레이아웃 개선
  app.config.ts
  src/app/(app)/chatting.tsx
  src/features/chatting/components/ChatHeader.tsx
  src/features/chatting/components/ChatInput.tsx
  src/features/chatting/containers/ChattingContainer.tsx
  src/features/chatting/hooks/useIsKeyboardOpen.ts
Labels: :sparkles: feature, 💅 design-tweak

#53 [dev <- hotfix] 캘린더, 일기 데이터 fetch 시 nullable하도록 수정
  src/features/chatting/hooks/mutations/useMakeThreadMutation.ts
  src/features/main/apis/diariesApi.ts
  src/features/main/components/DayComponent.tsx
  src/features/main/components/DiaryBottomSheet.tsx
  src/features/main/containers/MainContainer.tsx
  src/features/main/hooks/queries/useCalendarQuery.ts
  src/features/main/hooks/queries/useCalendarsQuery.ts
  src/features/main/hooks/queries/useDiariesQuery.ts
  src/features/main/types/calendarTypes.ts
  src/types/UtilTypes.ts
Labels: :bug: bug

#54 [dev <- hotfix] 설정 데이터를 가져오는 useQuery 2개의 queryFn 반환 타입 통일
  src/features/chatting/hooks/queries/useSleepTimeQuery.ts
Labels: :bug: bug

#55 [dev <- hotfix] aiProfileId를 백엔드에서 관리하도록 위임
  src/app/(app)/chatting.tsx
  src/constants/endpoint.ts
  src/features/assistantList/containers/AssistantListContainer.tsx
  src/features/assistantList/hooks/mutations/useRemoveAssistantMutation.ts
  src/features/assistantList/hooks/queries/useAssistantListQuery.ts
  src/features/chatting/containers/ChattingContainer.tsx
  src/features/chatting/hooks/mutations/useChangeAssistantMutation.ts
  src/features/chatting/hooks/queries/useAiProfileIdQuery.ts
  src/features/chatting/hooks/useChatting.ts
  src/features/chatting/hooks/useInitializeChatting.ts
  src/features/makeAssistant/apis/makeAssistantApi.ts
  src/features/makeAssistant/hooks/mutations/useMakeAssistantMutation.ts
  src/features/makeAssistant/hooks/queries/useMakeAssistantQuestionQuery.ts
  src/features/setting/hooks/mutations/useDeleteAccountMutation.ts
  src/features/setting/hooks/mutations/useLogoutMutation.ts
  src/libs/axiosInstance.ts
  src/libs/mmkv.ts
  src/libs/queryClient.ts
Labels: :bug: bug, :recycle: refactor

#56 [main <- dev] Melissa 1.0.1 (2)
  src/app/(app)/chatting.tsx
  src/constants/endpoint.ts
  src/features/assistantList/containers/AssistantListContainer.tsx
  src/features/assistantList/hooks/mutations/useRemoveAssistantMutation.ts
  src/features/assistantList/hooks/queries/useAssistantListQuery.ts
  src/features/chatting/containers/ChattingContainer.tsx
  src/features/chatting/hooks/mutations/useChangeAssistantMutation.ts
  src/features/chatting/hooks/mutations/useMakeThreadMutation.ts
  src/features/chatting/hooks/queries/useAiProfileIdQuery.ts
  src/features/chatting/hooks/queries/useSleepTimeQuery.ts
  src/features/chatting/hooks/useChatting.ts
  src/features/chatting/hooks/useInitializeChatting.ts
  src/features/main/apis/diariesApi.ts
  src/features/main/components/DayComponent.tsx
  src/features/main/components/DiaryBottomSheet.tsx
  src/features/main/containers/MainContainer.tsx
  src/features/main/hooks/queries/useCalendarQuery.ts
  src/features/main/hooks/queries/useCalendarsQuery.ts
  src/features/main/hooks/queries/useDiariesQuery.ts
  src/features/main/types/calendarTypes.ts
  src/features/makeAssistant/apis/makeAssistantApi.ts
  src/features/makeAssistant/hooks/mutations/useMakeAssistantMutation.ts
  src/features/makeAssistant/hooks/queries/useMakeAssistantQuestionQuery.ts
  src/features/setting/hooks/mutations/useDeleteAccountMutation.ts
  src/features/setting/hooks/mutations/useLogoutMutation.ts
  src/libs/axiosInstance.ts
  src/libs/mmkv.ts
  src/libs/queryClient.ts
  src/types/UtilTypes.ts
Labels: 🚀production

#58 [main] Melissa 1.0.2
  app.config.ts
Labels: 🚀production, 🔥hotfix

#57 [dev] 앱 버전 1.0.2로 업데이트 (IOS submit 실패 대응)
  app.config.ts
Labels: 🔥hotfix
